# Generated by Django 4.0.5 on 2022-06-14 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='leaves_create_model',
            new_name='LeavesCreateModel',
        ),
        migrations.RenameModel(
            old_name='leave_type',
            new_name='LeaveType',
        ),
    ]
