# Generated by Django 4.0.5 on 2022-06-14 07:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clone', '0002_rename_leaves_create_model_leavescreatemodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emp_personal',
            new_name='EmpPersonal',
        ),
        migrations.RenameModel(
            old_name='emp_self',
            new_name='EmpSelf',
        ),
    ]
