# Generated by Django 4.0.5 on 2022-06-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0003_rename_emp_personal_emppersonal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='harshit',
        ),
    ]
