# Generated by Django 4.0.5 on 2022-06-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0006_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetracker',
            name='ttl_hours',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
