# Generated by Django 4.0.5 on 2022-06-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0007_timetracker_ttl_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emppersonal',
            name='email',
            field=models.EmailField(blank=True, help_text='Employee personal email id', max_length=254),
        ),
    ]
