# Generated by Django 4.0.5 on 2022-06-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0008_alter_emppersonal_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavesandholidays',
            name='hrm_id',
        ),
    ]
