# Generated by Django 4.0.5 on 2022-06-24 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0011_alter_timetracker_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendenceRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('total_hours', models.TimeField(null=True)),
                ('status', models.BooleanField(help_text='user is active or not')),
            ],
        ),
        migrations.AlterModelOptions(
            name='attendence',
            options={'verbose_name_plural': 'attendence'},
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='checkin_time',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='checkout_time',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='ttl_work_time',
        ),
        migrations.AddIndex(
            model_name='attendence',
            index=models.Index(fields=['date'], name='clone_atten_date_6b627e_idx'),
        ),
        migrations.AddField(
            model_name='dailyattendencerecords',
            name='attendence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clone.attendence'),
        ),
    ]
